import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/GlobalComponents/Navbar';
import Footer from '@/components/GlobalComponents/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
          <div className="fixed z-40 w-full">
            <Navbar />
          </div>
          <main>{children}</main>
          <Footer />
        </main>
      </body>
    </html>
  );
}
