import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/GlobalComponents/Navbar';
import Footer from '@/components/GlobalComponents/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bg-[url("https://pixabay.com/get/g62060f60b0047d5aac2669a0783d2f349bbd28d872ac414716bb25ae0e400537465e0794d9f4276edd32c154b6884b1125f9c2db6a6a37b67c5a455f81282946_1920.jpg")]'>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </main>
      </body>
    </html>
  );
}
